[package]
name = "rust_lib_shopping_list_frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.36"
reqwest = "0.12.4"
serde = { version ="1.0.203", featues = ["derive"] }
serde_json = "1.0.117"
