[package]
name = "shopping_list_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.3"
actix-web = "4.6.0"
bson = "2.10.0"
futures = "0.3.30"
mongodb = "2.8.2"
serde_json = "1.0.117"
tokio = "1.37.0"
