// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'item_model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CommunicationRemote>>
abstract class CommunicationRemote implements RustOpaqueInterface {
  Future<void> addItem({required String name});

  Future<void> deleteItem({required String id});

  Future<List<Item>> getItems();

  factory CommunicationRemote() =>
      RustLib.instance.api.crateApiCommunicationCommunicationRemoteNew();

  Future<void> updateItem({required String id, required String newName});
}
