// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'item_model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Item>> getItems() =>
    RustLib.instance.api.crateApiCommunicationGetItems();

Future<void> deleteItem({required String id}) =>
    RustLib.instance.api.crateApiCommunicationDeleteItem(id: id);

Future<void> addItem({required String name}) =>
    RustLib.instance.api.crateApiCommunicationAddItem(name: name);
